<?php

namespace Test\Slevomat\Client;
use Slevomat\Client\Factory;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-11-15 at 23:34:55.
 */
class FactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Factory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Factory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Slevomat\Client\Factory::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        $this->object->create('{"result":false,"data":{},"error":{"code":1102,"message":"Invalid token was provided."}}', 403);
    }
}
