<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-11-16 at 12:16:23.
 */
class Slevomat_Client_ResponseFactoryTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Slevomat_Client_ResponseFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Slevomat_Client_ResponseFactory();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    public function badValues(): array
    {
        return [
            ['invalid json'],
            ['{"error": "true"}'],
            ['{"result":true,"data":"error","error":{"code":1102,"message":"Invalid token was provided."}}'],
            ['{"result":false,"data":{},"error":{}}']
        ];
    }

    /**
     * @covers Slevomat_Client_ResponseFactory::create
     */
    public function testCreate()
    {
        $this->object->create('{"result":false,"data":{},"error":{"code":1102,"message":"Invalid token was provided."}}',
            403);
    }

    /**
     * @dataProvider badValues
     * @expectedException RuntimeException
     * @covers Slevomat_Client_ResponseFactory::create
     */
    public function testCreateExeptions($badValue)
    {
        $this->object->create($badValue, 403);
    }
}
